
=head1 NAME

gdnsd.djbzones - gdnsd support for djbdns-style zone data

=head1 SYNOPSIS

As of this writing, djbdns file format support is considered
EXPERIMENTAL.  Feel free to submit issues and/or pull requests
to make the implementation more correct and/or complete!

/etc/gdnsd/djbzones/mydata:

    XXX

=head1 DESCRIPTION

XXX

=head1 SEE ALSO

L<gdnsd(8)>, L<gdnsd.config(5)>, L<gdnsd.zonefile(8)>

The gdnsd manual.

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2014 Brandon L Black <blblack@gmail.com>

This file is part of gdnsd.

gdnsd is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

gdnsd is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with gdnsd.  If not, see <http://www.gnu.org/licenses/>.

=cut
